name: Send SMS Every Minute

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-sms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Send SMS
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM_PHONE: ${{ secrets.TWILIO_FROM_PHONE }}
        run: python send_sms.py
